useGraphQL:
  playground: true
useMongoDB:
  uri: 'mongodb://localhost/void'

useTwilio:
  accountSid: AC5d0dd74c785a6a4e31448121bddb771c
  authToken: 9270fb959a650e079a8097a942a74d93
  verificationServiceSid: VAc50282a4cc7d4c002ecb31b6628cce1a
  phoneNumber: +17122170352

authentication:
  issuer: void.com
  privateKey: "-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEA4yQ9nQPd38sfZ4rVlBLNsQojECJXASna6S6rQWVeETueeToh\nS1Nqd8UlQBdl6tAjpzWN8X6+h+Mii9KWl3Cg2rZvbKbFi7nf0Rq4B/WfiH5jhPbb\nQXemMTxo+DrxohwiB/lGKliqkGj/TZgvhAp/TXvuPp6c6NlK+KVLK71CmWmGcgcS\n054plpbpr2UyWasTj1ZyaRUETakztORDbvskg/LK96aSpf9W52bTgeqw4R9j8xwn\n8izmYteEcy2zwovNMPZkMRjTW/XYovS2Da0Z/qFAcfkqTGqFeLoSOuFPfvHShEP5\n0UBuS6HisapclcRAW1OnfNc8Xez44dr6CmAmZwIDAQABAoIBAAcmaeYabA6SZ0+s\nGCMMIHt1NTtZyWFY/vIeLPfnB/oE5W0tfkTPwGc6xnxpACVPHgAyeGBku/ytErZS\nD7l+qyGXYpSJ/2fxlvEPJUHi4n26dMmHt8ksygd8vlUqDdcriYq0txe4KM5Y78hy\nhPRkHDPFNe+0sH3H8Us4cNBUqdcIYyuOsU9M3X6xMPNpovrbt7Hm3pJkuERhcErc\nIjDTzBS3pnagkIJPTDALZebsNs0QEN7mD/xWBP9dpWhuAWynTv5PMWaxUa7Ny0tw\ng5fn2tuDX3ekC8mtQ0ufxlhVtGTn7IsFDPUWHqrOT2h7ZFhl50UMBYKyp4OlKrHh\nza+FVmkCgYEA8LSVt4cbjGEsitZ8/8FfzZQAxLIonVtsaJaWNERBo+f816/Dcw8J\nVrSW5RfrGVSyLy1BPHu/OtLKxaCOjGEN2z8hmft+8yvl6+Yj12gDlz7F8kefnMSO\nzkO/oCNI2JJ73GzTKnrVy6E3bGbGIgoPWy7xBbt6B+36aOO9d5qDDUMCgYEA8ZMF\nSizYYvDVAlMQWr0vx9QNRlBjUtS9hDmtG1UqUAaWoDq65qXAdK13NnigcsiA0h/0\nH+dZxjHI5UgVrdBWpuq8IbUzk/sEH7XENVWxHBSVEnnUGglHbiGcgzQBmnZJW1te\ncoAaAbqM7s+R2oZ2xEuevzMim4UVJEaFzLow/g0CgYAPixm/6DGXNw8xR/h6a3pM\nRCpoiTimMKknd9HrPh0fAHQLWYY9f9MSjkbQNGMyF44KDdoQlc0bd1EwwdVyqzHB\n3qnEz8C64zLNsObPmh/hPGR76LQd43N1TlqpdJ3Xnl3xNfXM4HG93IM/tMNGn2+u\na7GUtS6EJJHvBAXQG2IrEQKBgBy1+YH4VHtl3hsZni76nywjwrQhp7xXdnK5nB5M\nf+vk7I/8iuwQtQ/o8esyaPdbZxwSGiSUjXHlxtehOppe0X2jFlr3OzsSMUpHgxtH\npPYOaC06939krO2k5wIc8zfVaSCHenEnUm/0KP3VA6OyKXlo92QIAsvzBDE8hHhx\nhJMdAoGALa352Y/uVickce/CuiR9zI6VXDtx1Pp/15EKEzYwWHGNoRlW6PfDuoUk\nGfk4I+Zd4hWk8EuxXoqZj41Pf9dTurI2GTGNqCRr3BbCelKRq4EE5jvnsVRkvcB1\n9RxI5JKSvSoYmLXmh2o4s4jBkS9E0tt2n127jWieZ31tIrWHs28=\n-----END RSA PRIVATE KEY-----"
  publicKey: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4yQ9nQPd38sfZ4rVlBLN\nsQojECJXASna6S6rQWVeETueeTohS1Nqd8UlQBdl6tAjpzWN8X6+h+Mii9KWl3Cg\n2rZvbKbFi7nf0Rq4B/WfiH5jhPbbQXemMTxo+DrxohwiB/lGKliqkGj/TZgvhAp/\nTXvuPp6c6NlK+KVLK71CmWmGcgcS054plpbpr2UyWasTj1ZyaRUETakztORDbvsk\ng/LK96aSpf9W52bTgeqw4R9j8xwn8izmYteEcy2zwovNMPZkMRjTW/XYovS2Da0Z\n/qFAcfkqTGqFeLoSOuFPfvHShEP50UBuS6HisapclcRAW1OnfNc8Xez44dr6CmAm\nZwIDAQAB\n-----END PUBLIC KEY-----"  
  useAccessToken:
    expiration: 5h
  useRefreshToken:
    expiration: 365d



useTwilio:
  accountSid: AC5d0dd74c785a6a4e31448121bddb771c
  authToken: 9270fb959a650e079a8097a942a74d93
  verificationServiceSid: VAc50282a4cc7d4c002ecb31b6628cce1a
  phoneNumber: +17122170352

authentication:
  issuer: void.com
  privateKey: "-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEA4yQ9nQPd38sfZ4rVlBLNsQojECJXASna6S6rQWVeETueeToh\nS1Nqd8UlQBdl6tAjpzWN8X6+h+Mii9KWl3Cg2rZvbKbFi7nf0Rq4B/WfiH5jhPbb\nQXemMTxo+DrxohwiB/lGKliqkGj/TZgvhAp/TXvuPp6c6NlK+KVLK71CmWmGcgcS\n054plpbpr2UyWasTj1ZyaRUETakztORDbvskg/LK96aSpf9W52bTgeqw4R9j8xwn\n8izmYteEcy2zwovNMPZkMRjTW/XYovS2Da0Z/qFAcfkqTGqFeLoSOuFPfvHShEP5\n0UBuS6HisapclcRAW1OnfNc8Xez44dr6CmAmZwIDAQABAoIBAAcmaeYabA6SZ0+s\nGCMMIHt1NTtZyWFY/vIeLPfnB/oE5W0tfkTPwGc6xnxpACVPHgAyeGBku/ytErZS\nD7l+qyGXYpSJ/2fxlvEPJUHi4n26dMmHt8ksygd8vlUqDdcriYq0txe4KM5Y78hy\nhPRkHDPFNe+0sH3H8Us4cNBUqdcIYyuOsU9M3X6xMPNpovrbt7Hm3pJkuERhcErc\nIjDTzBS3pnagkIJPTDALZebsNs0QEN7mD/xWBP9dpWhuAWynTv5PMWaxUa7Ny0tw\ng5fn2tuDX3ekC8mtQ0ufxlhVtGTn7IsFDPUWHqrOT2h7ZFhl50UMBYKyp4OlKrHh\nza+FVmkCgYEA8LSVt4cbjGEsitZ8/8FfzZQAxLIonVtsaJaWNERBo+f816/Dcw8J\nVrSW5RfrGVSyLy1BPHu/OtLKxaCOjGEN2z8hmft+8yvl6+Yj12gDlz7F8kefnMSO\nzkO/oCNI2JJ73GzTKnrVy6E3bGbGIgoPWy7xBbt6B+36aOO9d5qDDUMCgYEA8ZMF\nSizYYvDVAlMQWr0vx9QNRlBjUtS9hDmtG1UqUAaWoDq65qXAdK13NnigcsiA0h/0\nH+dZxjHI5UgVrdBWpuq8IbUzk/sEH7XENVWxHBSVEnnUGglHbiGcgzQBmnZJW1te\ncoAaAbqM7s+R2oZ2xEuevzMim4UVJEaFzLow/g0CgYAPixm/6DGXNw8xR/h6a3pM\nRCpoiTimMKknd9HrPh0fAHQLWYY9f9MSjkbQNGMyF44KDdoQlc0bd1EwwdVyqzHB\n3qnEz8C64zLNsObPmh/hPGR76LQd43N1TlqpdJ3Xnl3xNfXM4HG93IM/tMNGn2+u\na7GUtS6EJJHvBAXQG2IrEQKBgBy1+YH4VHtl3hsZni76nywjwrQhp7xXdnK5nB5M\nf+vk7I/8iuwQtQ/o8esyaPdbZxwSGiSUjXHlxtehOppe0X2jFlr3OzsSMUpHgxtH\npPYOaC06939krO2k5wIc8zfVaSCHenEnUm/0KP3VA6OyKXlo92QIAsvzBDE8hHhx\nhJMdAoGALa352Y/uVickce/CuiR9zI6VXDtx1Pp/15EKEzYwWHGNoRlW6PfDuoUk\nGfk4I+Zd4hWk8EuxXoqZj41Pf9dTurI2GTGNqCRr3BbCelKRq4EE5jvnsVRkvcB1\n9RxI5JKSvSoYmLXmh2o4s4jBkS9E0tt2n127jWieZ31tIrWHs28=\n-----END RSA PRIVATE KEY-----"
  publicKey: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4yQ9nQPd38sfZ4rVlBLN\nsQojECJXASna6S6rQWVeETueeTohS1Nqd8UlQBdl6tAjpzWN8X6+h+Mii9KWl3Cg\n2rZvbKbFi7nf0Rq4B/WfiH5jhPbbQXemMTxo+DrxohwiB/lGKliqkGj/TZgvhAp/\nTXvuPp6c6NlK+KVLK71CmWmGcgcS054plpbpr2UyWasTj1ZyaRUETakztORDbvsk\ng/LK96aSpf9W52bTgeqw4R9j8xwn8izmYteEcy2zwovNMPZkMRjTW/XYovS2Da0Z\n/qFAcfkqTGqFeLoSOuFPfvHShEP50UBuS6HisapclcRAW1OnfNc8Xez44dr6CmAm\nZwIDAQAB\n-----END PUBLIC KEY-----"  
  useAccessToken:
    expiration: 5h
  useRefreshToken:
    expiration: 365d



useAuth:
  secretKey: M0H@M^D_@BDULR@HM^N_S@MI_@LPH@_JUN0
  useCookies:
    expiration: 14400000
  useAccessToken:
    expiration: 4h
  useRefreshToken:
    expiration: 2d
generatedTokenConfig:
  registrationToken:
    secretKey: M0H@M^D_@BDULR@HM^N_S@MI_@LPH@_JUN0
    expiration: 5d
  forgotPasswordToken:
    secretKey: M0H@M^D_@BDULR@HM^N_S@MI_@LPH@_JUN0
    expiration: 24h
organizationInvitationAuth:
  useAccessToken:
    expiration: 5d
  callbackUrl: https://api.dev.pemo.io/api/v1/accept-invitation
mandrill:
  apiKey: tp2o2P2YlGvrf_iQu_I06A
  fromEmail: no-reply@pemo.io
  fromName: pemo
dapi:
  appSecret: 48c353b3ab66339b32f25f475da6ddb934828a4fe2a30abc516d86b72efd5f50
  appKey: 3e6445602728fb8ac28dc26a0dd14495bf7e96484bcb72c40c3df11688eb7a62
  ddToken:
server:
  port: 3000
  throttle:
    ttl: 10
    limit: 100
  apiPrefix: api/v1
  swagger:
    title: Pemo
    description: Pemo apis for integration with Open-Banking
    version: 1.0
    api: /api
    useAuth:
      username: pemo
      password: pemo
database:
  name: juno
  autoLoadModels: true
  synchronize: true
  dialect: postgres
  username: alpha_juno
  password: alphajunodb
  sync:
    force: false
  define:
    underscored: true
    paranoid: true
    timestamps: true
    freezeTableName: false
  pool:
    min: 2
    max: 10
cmsUrls:
  forgotPassword: 'https://app.dev.pemo.io/auth/reset-password'
  registrationInvitation: 'https://app.dev.pemo.io/auth/complete-business-info'
  acceptInvitation: 'https://app.dev.pemo.io/auth/accept-invitation'
pedant:
  baseUrl: 'https://api.dev.pedant.ai'
  uploadFileEndpoint: '/external/upload-file'
  authKey: 'f1d59faffa50bb69b867f35718f3417f91c4eb37643446e6b2cf16c348af255f'
s3:
  bucket: media-juno-dev
  cloudFront:
    privateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEAzA+KyjAqjjt6hNka6zKLJjEMtGWr3ceSPuyD2UfPXCSTnBH+
      I5PskmfIWOar+pIr/nrSHkosE/620T3s1paoBKaVfB8PN9rB/cIcoLohLVLt3ez6
      cgBK+JN3hVflKqy6m/HxHSK9HwcbNuiow0p407xfpviJB+mKjyuTu0MLxgFcE/qS
      6yySVykiH9EbWBNeElCUx7hzLoG5XZwttuRRuJNe+9hsVFhBqTyE5hjgJ3Vo/2aw
      Vlg9gQkpukCIc3ihRQzEnnDO/0KZVtwEM77811mfR2Bf4XHPFaOqxco++Q9sbwzW
      PgpG0E5KTIptK1AQSey4YoZKRYzHpv1RngQSnQIDAQABAoIBAHIAONRuBkhBuFfh
      hmVhblWez2804chcBzr6HUrVEGZ01LY7YxRzPpYoPshTzj6FTOi1qw9a9rcQ9Qd+
      pgLYVfOLMTYPkAvvPbNLr3ynn4NXsiXqj5wCx9+JWxt2mEO4DeSzTLWvQ6LC8JRD
      dIzt3QTFV1bLwJpYAZ2shbL3aOtrtWzwSR8IdBVSmtWE/uAnCVeeRmQu3W4iINMM
      5CD0oZGKEA1f+WBW2mNIQ51RRuolROUiGer9L0sd2PDfv6oM4qwViCkBUi1PrUhR
      DX7HWkxPVJHfBqju49pILbvwGvkZSRVGZQwKS32tbTTLfWWvbrryP3MQqKAS0ChP
      m4uzCkECgYEA7pb+3F3zBbNiXJ/3UfjfQR8/ykFbB/gEcsYxaaQxCEgjklIwxetL
      zJMfrmrnRI3FVNgUtX56+0jScKMw26U2gfyPtg7tUdg04jGXh4uAgiK3x4Z0wUGh
      RTLcyMVjPCZDR2dSJqlK2Q2SkkprWRmAF9djjV4laG0fbxRgVT73UG0CgYEA2vOF
      gxS4Qi7WKO65kkthuAH0T/qc7F67UQeD/7y/rFHSM5Ne+78Dq5amZKdOsXDIc+Zi
      lCEcwGOZNKYJcPuswMA2RIO29MLbxiaLc1oaGWDrQNCUE07ULQ0ZfJ98ltDWfdpy
      A+UpNTH2onbXg25GxstQZZSRWnBwMncUhd/1TPECgYAvYMCfVfCqUyLXLdTY7Ei5
      D9GFAlFnVbLcb8rkJXyvHlQh/Dw/MShOKXEDG6ttC5IB9R63o7QcLivLvjw3gak/
      Sr3m8zPhKsPlnt9uRR9xuB8yedq5faTeruj03W2FRjvZ9AR2NOvuCinu7uQ+PzgW
      g+j665UWFYVGc49lnilSSQKBgDeyILFScPis719kMqJrOIVVQe+iYY6jHmUjU0mX
      mu5btevWvh+t3GImpVcPVC5A8UzCOytRLP4nl85Tui0aaDxz6JoPI1gpxTwni+ug
      7OitxcosBK7Qq5p2LZiM/WVj5FwJWF1zSsM0XXfAYVwWjjx9dYsRetQVrAS6U+cm
      LEERAoGAHm8FHDFWkv4JVwFDkwlswv5qF8R8hq1IGfxyM74sfLZ+LP9tDswJ2mre
      4IJagKCPjBHMbsAGQ4GAyeqTQmny2aRotCfbUzVPDS79goQ1pcVNBHkp2LJk8fCd
      zjy8ZS0S1Y0+RyzCJro1+fhI/aUxR1tOU6Z3ElkgobUXneW5iGg=
      -----END RSA PRIVATE KEY-----
    domain: juno-media.dev.getjuno.io
    keyPairId: K29SHLISRSAFC
sesLambdaHash: '@Lambda123!'
swiftcodesapi:
  appKey: sk_c11439de84de3efa5dae842cbe8517124ca7878f9f8bd5cdca20eebd024ff01e
communicationEmails:
  invoiceLink: 'https://$$$.dev.pemo.io/invoice'
  failedInvoiceLink: 'https://$$$.dev.pemo.io/invoices-management/invoices'
  logo: 'https://media-pemo-prod.s3.eu-west-1.amazonaws.com/pemo.png'
quickbooks:
  clientKey: ABu1zX1IwFWFPMfp1Eco2NT9jJpezGrpfziUHk6kSVHKtgCnNg
  clientSecret: T3xZuux345Uz3nLpjKxPTPgy4aByruol0Q1wGoQJ
  sandbox: true
  debugging: false
  callbackUrl: 'https://api.dev.pemo.io/api/v1/organization-integration/quickbooks-callback'
  cmsUrl: 'https://$$$.dev.pemo.io/settings/accounting/'
  integrationToken:
    secretKey: very_secret_key
    expiration: 1h
fastForex:
  apiKey: 101f517287-1c0072cce9-r9efsc
